name: Custom release

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. 1.2.3)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      WORK_FOLDER: work-folder-very-unique-name

    steps:
      - name: Creating work folder
        id: create_wd
        run: mkdir "$WORK_FOLDER"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.WORK_FOLDER }}

      - name: Set Docker Login info
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          REGISTRY: "ghcr.io"
          PREFIX: "${{ github.repository_owner }}/nginx-kubernetes-ingress"
          TARGET: container
        #   TAG: "arm64_v${{ github.event.inputs.version }}"
          ARCH: arm64
        run: |
          # https://docs.nginx.com/nginx-ingress-controller/install/build/

          # docker buildx create --name mybuilder --driver docker-container --use
          make buildx-push-alpine
        working-directory: ${{ env.WORK_FOLDER }}

      - name: Set git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
        working-directory: ${{ env.WORK_FOLDER }}

      - name: Create Git tags
        run: |
          git tag -a v${{ github.event.inputs.version }} -m "Release v${{ github.event.inputs.version }}"
          git push origin v${{ github.event.inputs.version }}
        working-directory: ${{ env.WORK_FOLDER }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          generate_release_notes: true

      - name: Cleanup
        if: always() && steps.create_wd.outcome == 'success'
        run: rm -r "$WORK_FOLDER"